baseURL = 'https://islerm2-nku.github.io/CSC-640-MI-Part2/'
languageCode = 'en-us'
title = 'iRacing Telemetry API Documentation'
theme = 'hugo-book'

[params]
  description = 'FastAPI-based telemetry API with GitHub OAuth authentication'
  author = 'Mitchell Isler'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  
  [[menu.main]]
    name = 'Presentations'
    url = '/presentations/'
    weight = 2
  
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/islerm2-nku/CSC-640-MI-Part2'
    weight = 3
